Xml ng link
AllenNeuralDynamics/aind-ng-link pull request #11
Opened 2023-03-21 22:18 UTC by jwong-nd

Contains: 
- xml parser
- utility that compounds transforms (please check work here)
- refactored dispim example

2023-03-28 21:38 UTC, camilolaiton requested changes

2023-03-28 21:38 UTC, camilolaiton commented on src/ng_link/scripts/xml-link.py
> +def extract_xml_transforms(xml_path: str) -> dict[int, list[dict]]:
We use numpydoc documentation

2023-04-07 20:50 UTC, jwong-nd commented
Hello, this branch contains code to generate the exaspim ng-links, tested on the Exaspim 651324 dataset. 
I have placed this inside of the scripts/ folder as of now, let me know if there is a better place for this.

2023-04-07 23:58 UTC, carshadi approved these changes

2023-04-12 18:52 UTC, camilolaiton approved these changes

2023-04-12 18:54 UTC, merged