'blending on exaspim data, added dispim_link.py'
AllenNeuralDynamics/aind-ng-link pull request #13
Opened 2023-04-13 17:26 UTC by jwong-nd

adding code that generates a dispim ng link, see [https://aind-neuroglancer-sauujisjxq-uw.a.run.app#!s3://aind-open-data/diSPIM_647459_2022-12-07_00-00-00/process_output.json](https://aind-neuroglancer-sauujisjxq-uw.a.run.app/#!s3://aind-open-data/diSPIM_647459_2022-12-07_00-00-00/process_output.json). 

Generating dispim links is similar to exaspim links, with the addition of additional channels, co-registration between channels, and de-skewing. This script takes the existing exaspim_link.py and adds xml parsing of a co-registration XML, prepends these transforms to the net transform of each tile, and finally applies de-skewing. 

Next up, converting these scripts into a code ocean 'dataset_visualization' capsule.

2023-04-13 20:53 UTC, camilolaiton requested changes

2023-04-13 20:53 UTC, camilolaiton commented on src/ng_link/scripts/dispim_link.py
> +def apply_deskewing(matrix_3x4: np.ndarray, theta: float = 45) -> np.ndarray:
I believe the documentation is super important for the functions and the script itself. I encourage you to use the interrogate package to validate documentation

2023-04-18 16:06 UTC, camilolaiton approved these changes

2023-04-21 03:47 UTC, carshadi approved these changes

2023-04-25 16:35 UTC, merged