format link generation as module, defined all parameters
AllenNeuralDynamics/aind-ng-link pull request #14
Opened 2023-04-25 23:22 UTC by jwong-nd

moving scripting code into a module for calling inside a code capsule

2023-04-27 20:30 UTC, camilolaiton commented on src/ng_link/scripts/create_links.py
> +if __name__ == '__main__':
It's recommended to wrap the main inside of a main function

2023-04-27 20:31 UTC, camilolaiton commented on src/ng_link/dataset_links/__init__.py
> +__version__ = "0.0.1"
Is it necessary to have another module inside of scripts? If it's completely necessary, then there's no problem for now but we have to think if it's worth moving this inside of `ng_link`.

2023-04-27 20:35 UTC, camilolaiton requested changes
Hey Jonathan, amazing scripts. Could you please run the linters and fix what's necessary before I approve this? Thanks!

2023-04-27 22:38 UTC, jwong-nd commented
Not sure what the interrogate issue is, all functions have docstrings

2023-04-28 17:24 UTC, camilolaiton requested changes

2023-04-28 17:24 UTC, camilolaiton commented on pyproject.toml
> +    'neuroglancer',
Can we pin `numpy`, `neuroglancer`, `pint` and `xmltodict` dependencies?

2023-04-28 17:55 UTC, camilolaiton approved these changes

2023-04-28 18:00 UTC, merged